---

- name: Converge
  hosts: all
  vars:
    apache:
      sites:
        test1:
          domain: 'apache2.test.oxl.at'

          ssl:
            mode: 'snakeoil'
            cert:
              cn: 'Apache2'
              org: 'AnsibleGuy Test'
              email: 'testmaster@oxl.at'

  roles:
    - oxlorg.apache2
